
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: portfolio-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 

---


apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: portfolio-prod
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: portfolio-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          # Der Startbefehl für MinIO (Datenordner + Port für das Web-Dashboard)
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            # (Später auf dem Hetzner-Server ziehen wir die natürlich wieder aus dem K8s-Secret!)
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: MINIO_ROOT_PASSWORD
          volumeMounts:
            - name: minio-storage
              mountPath: /data
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-pvc