
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: portfolio-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 

---


apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: portfolio-prod
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: portfolio-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine 
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "portfoliodb"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: DB_PASSWORD
          # Hier sagen wir dem Container, wohin der Speicher gemountet wird
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc