
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seq-pvc
  namespace: portfolio-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 

---


apiVersion: v1
kind: Service
metadata:
  name: seq-service
  namespace: portfolio-prod
spec:
  selector:
    app: seq
  ports:
    - protocol: TCP
      port: 5341
      targetPort: 80 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq-deployment
  namespace: portfolio-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
        - name: seq
          image: datalust/seq:latest
          ports:
            - containerPort: 80
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SEQ_FIRSTRUN_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: SEQ_FIRSTRUN_ADMINPASSWORD
          volumeMounts:
            - name: seq-storage
              mountPath: /data
      volumes:
        - name: seq-storage
          persistentVolumeClaim:
            claimName: seq-pvc